import { Metadata } from "next"
import Login from "@/components/Login/Login"
export const metadata: Metadata = {
  title: 'University Management/login',
  description: 'Generated by create next app',
}

const LoginPage = () => {
  return (
    <div>
      <Login />
    </div>
  )
}
export default LoginPage